version: "3"

services: 
  msm-rest_api:
    image: $FULL_IMAGE_NAME:$TAG
    build: 
      context: .
    container_name: $IMAGE_NAME-$TAG
    ports: 
      - 3000:3000
    networks: 
      - atnet

networks:
  atnet: